#!/usr/bin/env just --justfile

update-deps:
  pnpm i @polkadot/networks@latest

update: update-deps

build:
  pnpm run build

link:
  pnpm link

publish:
  pnpm publish --access public

release: publish

c VERSION:
  git commit -am "Updated vuex-options@{{VERSION}}"

up: build publish

pack:
  pnpm pack
