#!/usr/bin/env just --justfile

update-deps:
  pnpm i -D typescript@latest
  pnpm i @polkadot/networks@latest

update: update-deps

build:
  pnpm run build

link:
  pnpm link

publish:
  pnpm publish --access public

c VERSION:
  git commit -am "Updated vuex-options@{{VERSION}}"

up: build publish
