#!/usr/bin/env just --justfile

update-deps:
  yarn add -D typescript@latest 
  yarn add @polkadot/networks@latest

update: update-deps

build:
  yarn build

link:
  yarn link

publish:
  yarn publish --access public

c VERSION:
  git commit -am "Updated vuex-options@{{VERSION}}"

up: build publish
