export enum InteractionV2 {
    ACCEPT = 'ACCEPT',
    BASE = 'BASE',
    EQUIP = 'EQUIP',
    EQUIPPABLE = 'EQUIPPABLE',
    LOCK = 'LOCK',
    RESADD = 'RESADD',
    SETPROPERTY = 'SETPROPERTY',
    SETPRIORITY = 'SETPRIORITY',
    THEMEADD = 'THEMEADD',

    BUY = 'BUY',
    EMOTE = 'EMOTE',
    CHANGEISSUER = 'CHANGEISSUER',
    SEND = 'SEND',
    LIST = 'LIST',
}