#!/usr/bin/env just --justfile

update-deps:
	npx npm-check-updates -u

update: update-deps

build: clear
  pnpm build

clear:
 @rm -rf ./dist

link:
  pnpm link

publish:
  pnpm publish --access public

c VERSION:
  git commit -am "Updated sub-api@{{VERSION}}"

pack:
  pnpm pack
