#!/usr/bin/env just --justfile

build:
  yarn build

link:
  yarn link

publish:
  yarn publish --access public

c VERSION:
  git commit -am ":bookmark: uniquery@{{VERSION}}"

up: build publish

update-deps:
  npx npm-check-updates -u
